Add update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,10 +19,9 @@ jobs:
         run: |
           set -e  # Ensure the script exits on any error
           new_version=$(python3 -m keepachangelog release) || exit_code=$?
-          if [[ ${exit_code:-0} -ne 0 ]]; then
-            echo "Python script failed with exit code ${exit_code:-0}"
-            echo "Performing cleanup actions"
-            exit ${exit_code:-0}  # Exit with the original exit code of the Python script
+          if [[ $exit_code -ne 0 ]]; then
+            echo "Python script failed with exit code $exit_code"
+            exit $exit_code  # Exit with the original exit code of the Python script
           else
             echo "new_version=${new_version}" >> "$GITHUB_OUTPUT"
             echo "Bumping version to ${new_version}"
